name: planta_client
description: Unofficial Dart client for the (Beta) Planta Public API
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  coverage: ^1.7.2
  custom_lint: ^0.7.3
  freezed: ^2.5.2
  freezed_lint: ^0.0.7
  json_serializable: ^6.9.0
  test: ^1.25.0
  very_good_analysis: ^7.0.0
